pipeline:
  cache-restore:
    image: peterdavehello/cdnjs-drone-ci
    action: restore-cache
    when:
      event: [ push, pull_request ]
  clone:
    image: peterdavehello/cdnjs-drone-clone:latest
    sparseCheckout: tools/sparse-checkout.template
  test:
    image: peterdavehello/cdnjs-drone-ci
    action: test
    when:
      event: [ push, pull_request ]
