pipeline:
  cache-restore:
    image: peterdavehello/cdnjs-drone-ci
    action: restore-cache
    when:
      event: [ push, pull_request ]
  clone:
    image: peterdavehello/drone-git-sparse-checkout:latest
    depth: 15
    sparseCheckout: tools/sparse-checkout-with-package.json.template
  test:
    image: peterdavehello/cdnjs-drone-ci
    action: test
    when:
      event: [ push, pull_request ]
